version: '2.2'

services:

  interview-localstack:
    image: localstack/localstack
    ports:
      - "4567-4597:4567-4597"
    environment:
      - DEFAULT_REGION=ap-southeast-1
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

